name: Type check terms on PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  fmc-type-check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install dependency
    - name: Install formality-core
      run: npm i formality-core
    
    - name: Type check fmc --github
      id: check_type_github
      run: node node_modules/formality-core/bin/fmc.js --github
    
    - name: Type check fm --github
      id: check_type_fm_github
      run: node node_modules/formality-core/bin/fm.js --github
          
