name: Update local files

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
  
   # Install dependency
    - name: Install formality-core
      run: npm i formality-core
      
    - name: Type check fm --github
      id: check_type_fm_github
      run: node node_modules/formality-core/bin/fm.js --github
      
    - name: Update .fmc
      uses: alexesprit/action-update-file@master
      with:
        file-path: .fmc
        commit-msg: Update .fmc with Github Action
        github-token: ${{ secrets.GITHUB_TOKEN }}
        allow-removing: true
   
    - name: Type check fmc --github
      id: check_type_github
      run: node node_modules/formality-core/bin/fmc.js --github
      
   

    
